### PR TITLE
Remove {} from Microservice

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by goldsborough** [comment]
I don't think that's valid syntax?

**Comment by pickfire** [comment]
It seems to compile here though. See https://doc.rust-lang.org/book/first-edition/structs.html#unit-like-structs

Still, thanks a lot for the great article.

**Comment by pickfire** [comment]
As well, https://github.com/tokio-rs/tokio-minihttp/blob/master/examples/hello-world.rs#L42

**Comment by pickfire** [comment]
@goldsborough Is this available for merged? I have others patches to send in though.

**Comment by goldsborough** [comment]
I really don't think this is valid Rust. It may have been in an older version. The link you gave is the first edition of the Rust book. Just try it out here https://godbolt.org/g/z9tN94

**Comment by steveklabnik** [comment]
```
pub struct X {}
```

This is the difference. If it was defined as

```
pub struct X;
```

then this works. In this case, `Microservice` is, so it should work just fine.

(Your godbolt also uses Rust 1.9; this syntax was added at some point, so it may also be that 1.9 is too old.)

**Comment by pickfire** [comment]
@goldsborough Maybe it should have been tested with rust 1.21 and above (I am using 1.24.1 here)?

Edit: https://godbolt.org/g/WJ7J4n works thanks to emerentius.

**Comment by goldsborough** [comment]
Thanks for the clarification @pickfire and @steveklabnik ! Sorry for the delay on my side

**Pull request merged**
